os: linux
dist: jammy
language: node_js
node_js:
  - 16
services:
  - docker

before_install: 
  - docker build -t igorlucenan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true igorlucenan/docker-react npm run test